status = ["ci (stable, false, --all-features)", "ci (beta, false, --all-features)", "ci (1.52.1, false, --all-features)", "clippy_check", "rustfmt", "audit_check", "licensing (bans licenses sources)"]
pr_status = ["ci (stable, false, --all-features)", "ci (beta, false, --all-features)", "ci (1.52.1, false, --all-features)", "clippy_check", "rustfmt", "audit_check", "licensing (bans licenses sources)"]
timeout_sec = 1800
use_squash_merge = false
block_labels = ["wip"]
delete_merged_branches = true
update_base_for_deletes = true
